### ISSUE TITLE
Mite and App::FatPacker not working

### ISSUE THREAD

**Issue by Sadrak** [tobyink/p5-mite#34]
with fatpacker you can build a nice executable with dependencies. Our scripts stop working after MooX::Late switched from MooX::HandlesVia to Sub::HandlesVia.

Sub::HandlesVia use Mite and try to load some *.mite.pm files depends on the caller file, which won't work from the view of fatpacker.

Here is a short dependency example of the file fatpacked:
```perl
$fatpacked{"Sub/HandlesVia/Mite.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'SUB_HANDLESVIA_MITE';
...
$fatpacked{"Sub/HandlesVia/Toolkit/Moo.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'SUB_HANDLESVIA_TOOLKIT_MOO';
...
$fatpacked{"Sub/HandlesVia/Toolkit/Mite.pm.mite.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'SUB_HANDLESVIA_TOOLKIT_MITE.PM.MITE';
...
```

executing the fatpacked file will result in fatpacked.mite.pm not found
```
Compiled Mite file (fatpacked.mite.pm) for fatpacked is missing at fatpacked line 51015
```

The reason is Sub::HandlesVia::Mite::import() which used the file from caller():
```perl
  package Sub::HandlesVia::Mite;
  ...
  sub import {
      my $me = shift;
      my %arg = map { lc($_) => true } @_;
      my ( $caller, $file ) = caller;
      ...
          my $mite_file = $file . ".mite.pm";
          if( !-e $mite_file ) {
              croak "Compiled Mite file ($mite_file) for $file is missing";
          }
  
          {
              local @INC = ('.', @INC);
              require $mite_file;
          }
...
```

After some debugging i found the following files that import try to require:
Sub::HandlesVia::Toolkit::Moo fatpacked
Sub::HandlesVia::Toolkit fatpacked
Sub::HandlesVia::Handler fatpacked
Sub::HandlesVia::Handler::Traditional fatpacked
Sub::HandlesVia::Handler::CodeRef fatpacked

Adding some code to load from the package part from caller and ignoring subclasses of Handler::* everything started working again.

```perl
...
print STDERR "\n\t$caller $file\n\n";
$file = $caller;
$file =~ s/Handler\K::.+$//;
$file =~ s/::/\//g;
$file .= ".pm";
          my $mite_file = $file . ".mite.pm";
#          if( !-e $mite_file ) {
#              croak "Compiled Mite file ($mite_file) for $file is missing";
#          }
  
          {
              local @INC = ('.', @INC);
              eval {
                  require $mite_file;
              };
              if ($@) {
                  croak "Compiled Mite file ($mite_file) for $file is missing or $@";
              }
          }
...
```

I also don't understand why there is a previous check for not found $mite_file, because require has a good error. Perhaps it would be better to eval {} the require and add additional infos when an error occur? This would easier to build a workaround for the first problem.

**Comment by tobyink** [comment]
Yeah, I don't know why that file existence check is in there. (It was in the original Mite v0.0.1 which I took over maintenance of.)

**Comment by tobyink** [comment]
Released Mite 0.012000 which loads the ".mite.pm" file in a more sensible way.

I'll release a new Sub::HandlesVia in the next few days as I'm in the middle of adding a new feature to it.

**Comment by Sadrak** [comment]
Thanks for the quick reaction. But it still uses $file from caller(), which is always fatpacked in my case and not the required class.

Are you planing to add also some better solution (using $class from caller()) or should i build a workaround?

**Comment by tobyink** [comment]
Using the package name from the caller would be a change of behaviour as it would prevent multiple Mite-based packages from being defined in the same file.

You may need to add something like this to your script:

```perl
BEGIN {
  $INC{'fatpacked.mite.pm'} = 1;
  require($_) for qw(
    Sub/HandlesVia/Toolkit/Mite.pm.mite.pm
  );
};
```

**Comment by Sadrak** [comment]
> Using the package name from the caller would be a change of behaviour as it would prevent multiple Mite-based packages from being defined in the same file.

There is nothing bad from my view in using more files. The current way is wrong for users with packers or users who try to overload modules (perhaps). Not using the class/package name to load additional code for a class/package will result in some strange problems for your users in special cases.

I have now a running workaround, thanks a lot!

**Comment by tobyink** [comment]
Sub::HandlesVia is now rebuilt with the latest version of Mite.

**Comment by Sadrak** [comment]
Thanks a lot. I guess a change to loading with class names is not desired so i close this ticket.
